pipeline:
  test:
    image: python:${PYTHON_VERSION}
    pull: true
    group: build
    environment:
      - SILVER_DB_ENGINE=django.db.backends.mysql
      - SILVER_DB_NAME=test_db
      - SILVER_DB_HOST=mysql
      - SILVER_DB_USER=silver
      - SILVER_DB_PASSWORD=silver
    commands:
      - make dependencies
      - pip install -U "Django${DJANGO_VERSION}"
      - mkdir /var/log/silver
      - make lint
      - make test

  publish-docker:
    image: plugins/docker
    group: publish
    repo: presslabs/silver
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    force_tag: true
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    when:
      event: [push, tag]

  trigger-docs-build:
    image: plugins/downstream
    server: https://drone.presslabs.net
    fork: true
    secrets: [DRONE_TOKEN]
    repositories:
      - presslabs/docs
    when:
      branch: master
      event: push
      matrix:
        PYTHON_VERSION: 3.8
        DJANGO_VERSION: ">=3.1,<3.2"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=silver
      - MYSQL_PASSWORD=silver
  redis:
    image: redis:3-alpine

matrix:
  include:
    - PYTHON_VERSION: 3.7
      DJANGO_VERSION: ">=3.1,<3.2"
    - PYTHON_VERSION: 3.8
      DJANGO_VERSION: ">=3.1,<3.2"
    - PYTHON_VERSION: 3.7
      DJANGO_VERSION: ">=3.2,<3.3"
    - PYTHON_VERSION: 3.8
      DJANGO_VERSION: ">=3.2,<3.3"