dist: xenial
language: python
services: redis-server

git:
  submodules: false

python:
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=">=3.1,<3.2"
  - DJANGO_VERSION=">=3.2,<3.3"

cache: pip

install:
  - pip install -U -r requirements/test.txt
  - pip install -U "Django$DJANGO_VERSION"

script:
  - make lint
  - make test
